services:
  db:
    image: postgres:16-alpine
    container_name: pekarnya-db
    environment:
      POSTGRES_DB: pekarnya
      POSTGRES_USER: pekar
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: pekarnya-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pekarnya
      SPRING_DATASOURCE_USERNAME: pekar
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
