name: frontend-lint

on:
  pull_request:
    branches: [dev, main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'
      - '.eslintrc*'
      - '.prettier*'
      - '.stylelintrc*'
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'
      - '.eslintrc*'
      - '.prettier*'
      - '.stylelintrc*'

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      # c кешем, если есть package-lock.json
      - name: Setup Node (with cache)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # без кеша, если lock нет
      - name: Setup Node (no cache)
        if: ${{ hashFiles('frontend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install deps
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then npm ci; else npm install; fi
          else
            echo "No package.json — nothing to install"; fi

      - name: ESLint
        run: |
          if npm run | grep -q "lint"; then npm run lint; else echo "no lint script — skipping"; fi

      - name: Prettier (check)
        run: |
          if npm run | grep -q "format:check"; then npm run format:check; else echo "no format:check — skipping"; fi

      - name: Stylelint (optional)
        run: |
          if [ -f "./.stylelintrc.json" ] || [ -f "./.stylelintrc" ]; then
            if npm run | grep -q "stylelint"; then npm run stylelint; else echo "no stylelint script — skipping"; fi
          else
            echo "stylelint config not found — skipping"
          fi
