name: frontend-unit-tests

on:
  pull_request:
    branches: [dev, main]
    paths:
      - frontend/**
      - .github/workflows/frontend-unit-tests.yml
  push:
    branches: [dev]
    paths:
      - frontend/**
      - .github/workflows/frontend-unit-tests.yml
  workflow_dispatch: {}

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Run tests (if script exists)
        run: |
          TEST_SCRIPT=$(npm pkg get scripts.test | tr -d '"')
          if [ "$TEST_SCRIPT" != "null" ]; then
            npm test -- --ci
          else
            echo "No 'test' script — skipping"
          fi
