name: frontend-lint

on:
  pull_request:
    branches: [dev, main]   # запускаем на любом PR
  push:
    branches: [dev]         # и на пуши в dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stub lint (no-op)
        run: |
          echo "Frontend lint stub running..."
          echo "No frontend project detected or lint disabled for now."
          exit 0
